-- ============================================================
-- Portal da Transparência MA - Seed: Top 100 termos buscados
-- ============================================================
-- Migration: 20260425140000_seed_termos_buscados
-- Fonte: Planilha Termos_Buscados_Consolidado.xlsx (cedida pela STC)
-- Filtro de segurança: termos com aparência de CPF/CNPJ pulados
-- ============================================================

INSERT INTO public.termos_buscados (termo, termo_normalizado, total_buscas) VALUES
  ('Remuneração', 'remuneracao', 10948),
  ('Norcia vigilância patrimonial', 'norcia vigilancia patrimonial', 4646),
  ('Folha de pagamento', 'folha de pagamento', 4449),
  ('Fast Ambiental', 'fast ambiental', 3148),
  ('servidores', 'servidores', 2792),
  ('NILMA', 'nilma', 2408),
  ('contratos', 'contratos', 2365),
  ('Uemasul', 'uemasul', 2321),
  ('EJATEC', 'ejatec', 2097),
  ('Salário', 'salario', 1920),
  ('Funac', 'funac', 1814),
  ('servidor', 'servidor', 1611),
  ('emserh', 'emserh', 1599),
  ('Procon', 'procon', 1472),
  ('HSLZ', 'hslz', 1377),
  ('licitação', 'licitacao', 1264),
  ('Por-', 'por-', 1248),
  ('Martins e reis', 'martins e reis', 1199),
  ('Orlando Barbosa Filho', 'orlando barbosa filho', 1147),
  ('Contra cheque', 'contra cheque', 1138),
  ('salario', 'salario', 1100),
  ('Diárias', 'diarias', 1019),
  ('2025', '2025', 1018),
  ('diarias', 'diarias', 1000),
  ('Professor', 'professor', 979),
  ('Casa de Saúde e Maternidade de Caxias', 'casa de saude e maternidade de caxias', 924),
  ('Alexsandro da Silva Sousa', 'alexsandro da silva sousa', 913),
  ('despesas', 'despesas', 860),
  ('2026', '2026', 815),
  ('Iema', 'iema', 808),
  ('Delegado', 'delegado', 806),
  ('licitações', 'licitacoes', 797),
  ('naiara araujo', 'naiara araujo', 795),
  ('Maria de Fátima Santos Pereira', 'maria de fatima santos pereira', 794),
  ('martins e reis ltda', 'martins e reis ltda', 788),
  ('pessoal', 'pessoal', 705),
  ('JODSON SANTOS MACHADO', 'jodson santos machado', 671),
  ('juscelino de abreu passos', 'juscelino de abreu passos', 659),
  ('Francisco Coelho dos Santos Junior', 'francisco coelho dos santos junior', 614),
  ('restaurante popular', 'restaurante popular', 602),
  ('Investigador', 'investigador', 588),
  ('Seap', 'seap', 582),
  ('Milena Moura Reinaldo', 'milena moura reinaldo', 573),
  ('Uema', 'uema', 570),
  ('folha', 'folha', 559),
  ('Mensageiro da paz', 'mensageiro da paz', 556),
  ('HSE', 'hse', 532),
  ('Ronaldi Jouberth Diniz Madeira', 'ronaldi jouberth diniz madeira', 519),
  ('Carlos Brandão', 'carlos brandao', 505),
  ('moisanielton', 'moisanielton', 504),
  ('Pvcantor', 'pvcantor', 504),
  ('centro cultural Divino espírito santo da liberdade', 'centro cultural divino espirito santo da liberdade', 499),
  ('2024', '2024', 486),
  ('Remuneração de servidores', 'remuneracao de servidores', 484),
  ('Jorgeilson costa frazao', 'jorgeilson costa frazao', 475),
  ('Jarcio de souza', 'jarcio de souza', 464),
  ('contrato', 'contrato', 459),
  ('Detran', 'detran', 457),
  ('Salários', 'salarios', 443),
  ('Instituto Euvaldo lodi e sema', 'instituto euvaldo lodi e sema', 439),
  ('Carnaval', 'carnaval', 432),
  ('Secma', 'secma', 424),
  ('UEMASUL PPGLE', 'uemasul ppgle', 424),
  ('Nikson daniel Souza da Silva', 'nikson daniel souza da silva', 420),
  ('remuneracao', 'remuneracao', 418),
  ('Caema', 'caema', 418),
  ('qualitech', 'qualitech', 417),
  ('Cayamba', 'cayamba', 416),
  ('Remuneração dos servidores', 'remuneracao dos servidores', 403),
  ('Soldado', 'soldado', 401),
  ('Despesas Raça segurança 2022', 'despesas raca seguranca 2022', 399),
  ('José Wilson machado paixão', 'jose wilson machado paixao', 397),
  ('Encanto do São Cristóvão', 'encanto do sao cristovao', 395),
  ('Rosa branca', 'rosa branca', 382),
  ('Norcia', 'norcia', 378),
  ('Seduc', 'seduc', 374),
  ('Auditor fiscal', 'auditor fiscal', 374),
  ('Rivangelio Rodrigues Almeida', 'rivangelio rodrigues almeida', 373),
  ('João Willian Ferreira Bonfim', 'joao willian ferreira bonfim', 370),
  ('Remuneração servidores', 'remuneracao servidores', 365),
  ('salarios', 'salarios', 357),
  ('Cultura', 'cultura', 356),
  ('Rebeca de Brito Fernandes', 'rebeca de brito fernandes', 355),
  ('cfo', 'cfo', 350),
  ('Opinião', 'opiniao', 347),
  ('Larissa Cristina de Castro Santana', 'larissa cristina de castro santana', 346),
  ('IEL e sema', 'iel e sema', 341),
  ('C&S vigilância e segurança', 'c&s vigilancia e seguranca', 338),
  ('esporte', 'esporte', 338),
  ('perito criminal', 'perito criminal', 332),
  ('Rm terceirização', 'rm terceirizacao', 330),
  ('Brilho da balaiada', 'brilho da balaiada', 330),
  ('Daniel Maranhão Meneses', 'daniel maranhao meneses', 329),
  ('Brilho do amanhecer', 'brilho do amanhecer', 327),
  ('Portal da transparência', 'portal da transparencia', 327),
  ('Landia pereira da silva', 'landia pereira da silva', 318),
  ('allisson gomes guimarães', 'allisson gomes guimaraes', 317),
  ('Vigilância armada C&S filial', 'vigilancia armada c&s filial', 312),
  ('ibrapp', 'ibrapp', 311),
  ('HILIAS LIMA BOSCOS', 'hilias lima boscos', 310)
ON CONFLICT (termo) DO UPDATE SET total_buscas = EXCLUDED.total_buscas;
